apiVersion: v1
kind: Pod
metadata:
  name: test-a3redis
spec:
  containers:
  - image: threekinds/python:3.8-ubuntu
    name: python3
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "trap : TERM INT; sleep infinity & wait" ]
    volumeMounts:
    - mountPath: /a3redis
      name: a3redis-dir
  restartPolicy: OnFailure
  volumes:
  - name: a3redis-dir
    hostPath:
      path: /host/gitee/a3/a3redis
